### ISSUE TITLE
Is it possible to set the column is required?

### ISSUE THREAD

**Issue by vip30** [mibrito/joi-sequelize#2]
Which the column is not null,
Thanks!

**Comment by mibrito** [comment]
Hi vip30,

I think joi-sequelize handle all not null sequelize's fields as joi's required field by default. If you for any reason want some sort of "soft consistency" in a nullable sequelize field, I may advice you to use a [built in joi's function](https://github.com/hapijs/joi/blob/v9.0.0-3/API.md#objectrequiredkeyschildren) over joi-sequelize generated schema to your specific route, otherwise I don't see a reason to not ensure that by default in your sequelize model (and consequently with joi-sequelize schema to all routes) nor your data schema.

I hope I had answered your doubt.

**Comment by vip30** [comment]
test

**Comment by vip30** [comment]
But I think that if I set the model like that
    method: 'POST',
    path: '/users',
    handler:(request,reply)=>reply(request.payload),
    config:  {
      validate: {
        payload: {
            firstname: Joi.string().required()
        }
And if the payload do not have "firstname", It will warning that it's required.

However, when I change that to joi-sequelize model as below,
      validate: {
        payload:  new JoiSequelize(User).joi(),
      }
which the model is 
  var User = sequelize.define("Users", {
        user_id: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        firstname: {
            type: DataTypes.STRING,
            allowNull: false
        },.......
It will never prompt the firstname is required

BTW, in the joi-sequelize define.js,
I can't find "required" but just allow null.
Sorry for a long question.
Thanks!

**Comment by mibrito** [comment]
Sorry for take so long to answer your question.
To solve your problem, I've created a function called withRequired that return all allowNull:false as required on you joi schema.
